### ISSUE TITLE
externRefManager/hostFunctionManager does NOT handle reuse elements properly

### ISSUE THREAD

**Issue by chenhengqi** [second-state/WasmEdge-go#11]
This implementation here seems to be wrong ?

https://github.com/second-state/WasmEdge-go/blob/87a58325196d611e296780f43de2abd8b0804d41/wasmedge/value.go#L91-L93

https://github.com/second-state/WasmEdge-go/blob/87a58325196d611e296780f43de2abd8b0804d41/wasmedge/hostfunc.go#L42-L44

The last element is reused, but not pop out from the slice.

**Comment by hydai** [comment]
Thanks for reporting.

@q82419 could you please check this?

**Comment by q82419** [comment]
Thanks for reporting. Will be fixed in PR.
