### ISSUE TITLE
invalid version: unknown revision wasmedge/v0.10.0

### ISSUE THREAD

**Issue by authenticz** [second-state/WasmEdge-go#31]
I used the command you provided in Getting Started:
`go get github.com/second-state/WasmEdge-go/wasmedge@v0.10.0`
but failed. The error message is:
> go get: github.com/second-state/WasmEdge-go/wasmedge@v0.10.0: invalid version: unknown revision wasmedge/v0.10.0

and I also tried setting up GOPRIVATE according to the method described in this website:https://stackoverflow.com/questions/67678203/why-does-go-get-fail-with-invalid-version-unknown-revision
but still failed for the same reason.
And i noticed that you just published the v0.10.0 version a few days ago, and it's only pre-release. Is that caused my problem?

**Comment by hydai** [comment]
Hi @dakexiaoying 
After WasmEdge released 0.10.0, we found that the installer script has a bug: https://github.com/WasmEdge/WasmEdge/issues/1497

That's why the WasmEdge-go doesn't release its 0.10.0. We are going to fix the installer script first and then release wasmedge-go v0.10.0.

**Comment by dakexiaoying** [comment]
邮件已收到，谢谢。

**Comment by chairwa** [comment]
I use WasmEdge 0.10.0 and WasmEdge-go 0.9.2 to run 
https://github.com/yomorun/yomo-wasmedge-tensorflow

go run -tags tensorflow,image app.go
# github.com/second-state/WasmEdge-go/wasmedge
../../../../go/pkg/mod/github.com/second-state/!wasm!edge-go@v0.9.2/wasmedge/executor.go:122:9: could not determine kind of name for C.WasmEdge_ExecutorInvokeRegistered
../../../../go/pkg/mod/github.com/second-state/!wasm!edge-go@v0.9.2/wasmedge/executor.go:64:9: could not determine kind of name for C.WasmEdge_ExecutorRegisterModule

What should I do to workaround?

**Comment by hydai** [comment]
The WasmEdge-go is strictly matched to the corresponding WasmEdge SDK version.
So you cannot use WasmEdge 0.10.0 with WasmEdge-go 0.9.2.
To fix this, please downgrade the WasmEdge version to 0.9.1 (because the 0.9.2 is a hotfix version only on WasmEdge-go)

**Comment by chairwa** [comment]
WasmEdge states "Image Extensions not supported".

go run -tags "tensorflow image" app.go
# github.com/second-state/WasmEdge-go/wasmedge
../../../../go/pkg/mod/github.com/second-state/!wasm!edge-go@v0.9.2/wasmedge/extension_image.go:8:10: fatal error: wasmedge/wasmedge-image.h: No such file or directory
    8 | #include <wasmedge/wasmedge-image.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by hydai** [comment]
What's your platform?
If you are on macOS, then you have to wait for the WasmEdge-go release 0.10.0.

https://github.com/WasmEdge/WasmEdge/blob/master/utils/install.sh#L457-L481

**Comment by chairwa** [comment]
> What's your platform?

aarch64 Ubuntu 20.04.4 LTS

**Comment by hydai** [comment]
Very wired. Maybe this is an installer script issue.
For the Ubuntu aarch64, we have supported it in 0.9.1.
https://github.com/second-state/WasmEdge-image/releases/tag/0.9.1


Could you raise a new issue and paste the detailed logs here: https://github.com/WasmEdge/WasmEdge/issues/new?assignees=&labels=&template=bug_report.md

**Comment by chairwa** [comment]
https://github.com/WasmEdge/WasmEdge/issues/1501

**Comment by q82419** [comment]
Fixed.
