### ISSUE TITLE
Why wasmedge-tensorflow & wasmedge-tensorflowlite necessary at the same time?

### ISSUE THREAD

**Issue by chairwa** [second-state/WasmEdge-go#32]
https://github.com/second-state/WasmEdge-go/blob/e23f36ed9cf520eacb7d3cd6b2f02d14c0b920c9/wasmedge/extension_tensorflow.go#L9

wasmedge-tensorflow & wasmedge-tensorflowlite are required at the same time by the above code.
This way, we cannot use WasmEdge-go tensorflowlite extension on aarch64 linux, where only tensorflowlite provided.

**Comment by chairwa** [comment]
@q82419

**Comment by q82419** [comment]
The WasmEdge-Go is designed for x86_64 platforms in current.
We'll improve this for supporting more platforms and architectures in the future.
Thanks.
