### ISSUE TITLE
Compatibility with wasmedge 0.12.0 pre-releases

### ISSUE THREAD

**Issue by loredanacirstea** [second-state/WasmEdge-go#39]
WasmEdge-go 0.11.2 is not compatible with WasmEdge 0.12.0 alpha pre-releases.

(I wanted to try the latest WasmEdge, to see if an AOT compilation out-of-bounds error was still happening. But I cannot test it in my Golang setup.)

**Comment by q82419** [comment]
Hi,
We're working on this in these days. Thanks!

**Comment by hydai** [comment]
This is fixed.
