### ISSUE TITLE
 wasmedge/wasmedge.h: No such file or directory

### ISSUE THREAD

**Issue by Alps-Sun** [second-state/WasmEdge-go#40]
I've been folowing the  instructions [yomo-wasmedge-tensorflow](https://github.com/yomorun/yomo-wasmedge-tensorflow)  with go run --tags "tensorflow image" app.go and it fails with this error message:

```
# github.com/second-state/WasmEdge-go/wasmedge
/root/go/pkg/mod/github.com/second-state/!wasm!edge-go@v0.12.0/wasmedge/ast.go:3:11: fatal error: wasmedge/wasmedge.h: No such file or directory
    3 | // #include <wasmedge/wasmedge.h>
      |           ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

```

**Comment by hydai** [comment]
Do you install wasmedge dependencies in these steps? https://github.com/yomorun/yomo-wasmedge-tensorflow#steps-to-run

**Comment by hydai** [comment]
This issue was closed because it has been inactive.
